<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
      <PackageReference Include="StackExchange.Redis" Version="3.0.2-preview" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CleanWebApiTemplate.Application\CleanWebApiTemplate.Application.csproj" />
      <ProjectReference Include="..\CleanWebApiTemplate.Domain\CleanWebApiTemplate.Domain.csproj" />
    </ItemGroup>

</Project>
