<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="UseCases\Users\UpdateUser\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CleanWebApiTemplate.Domain\CleanWebApiTemplate.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mapster" Version="10.0.7" />
      <PackageReference Include="Mediator.Abstractions" Version="3.1.0-rc.1" />
      <PackageReference Include="Mediator.SourceGenerator" Version="3.1.0-rc.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    </ItemGroup>

</Project>
